# https://docs.pypi.org/trusted-publishers/using-a-publisher/
# https://docs.astral.sh/uv/guides/integration/github/

name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Python
        run: uv python install 3.12

      - name: Sync dependencies
        run: uv sync --group dev

      - name: Ruff
        run: uv run ruff check .

      - name: MyPy
        run: uv run mypy .

      - name: Pytest
        run: uv run pytest --cov=task_logging --cov-report=term-missing\

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish
